Missing LICENSE
php-translation/translator pull request #18
Opened 2018-07-20 07:48 UTC by Korbeil

Adding missing LICENSE file.

2018-08-06 13:02 UTC, bocharsky-bw requested changes
I suppose it should be under MIT, probably we can just copy/paste from here: https://github.com/php-translation/converter/blob/master/LICENSE

2018-08-09 18:22 UTC, Korbeil commented
@bocharsky-bw fixed ;-)

2018-08-09 18:32 UTC, Nyholm approved these changes

2018-08-09 18:32 UTC, Nyholm commented
Thank you

2018-08-09 18:32 UTC, merged